[auth]
redirect_uri = "http://localhost:8501/oauth2callback"
cookie_secret = "supersecretkeyforcookie"
client_id = "5c7d9889e143ced58f63f86e60376db1"
client_secret = "5c7d9889e143ced58f63f86e60376db138ec3a8462106b51db32daa7be74696be9f48f87e5695b42b5126a8ef11d1e14"
server_metadata_url = "https://63557302.propelauthtest.com/.well-known/openid-configuration"
client_kwargs = { "prompt" = "login" } # Optional.
# Will force the user to go through the login flow.
